Name:           perl-File-Monitor-Lite
Version:        0.652003
Release:        1%{?dist}
Summary:        Monitor file changes
License:        CHECK(GPL+ or Artistic)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/File-Monitor-Lite/
Source0:        http://www.cpan.org/authors/id/D/DR/DRYMAN/File-Monitor-Lite-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Class::Accessor::Fast)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Find::Rule)
BuildRequires:  perl(File::Monitor)
BuildRequires:  perl(File::Spec::Functions)
BuildRequires:  perl(File::Touch)
Requires:       perl(Class::Accessor::Fast)
Requires:       perl(File::Find::Rule)
Requires:       perl(File::Monitor)
Requires:       perl(File::Spec::Functions)
Requires:       perl(File::Touch)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This is another implementaion of File::Monitor. While File::Monitor cannot
detect file creation (unless you declare file name first), I use
File::Find::Rule to rescan files every time when $monitor->check() is
executed. To use this module, just follow synopsis above.

%prep
%setup -q -n File-Monitor-Lite-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README.mkd
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Apr 06 2017 Tom Schoonjans 0.652003-1
- Specfile autogenerated by cpanspec 1.78.
