Name:           perl-Pod-ProjectDocs
Version:        0.45
Release:        1%{?dist}
Summary:        Generates CPAN like project documents from pod
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Pod-ProjectDocs/
Source0:        http://www.cpan.org/authors/id/M/MG/MGRUNER/Pod-ProjectDocs-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Class::Accessor::Fast)
BuildRequires:  perl(Class::Data::Inheritable)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(JSON) >= 2.04
BuildRequires:  perl(Pod::Parser) >= 1.32
BuildRequires:  perl(Pod::ParseUtils)
BuildRequires:  perl(Readonly)
BuildRequires:  perl(Template)
BuildRequires:  perl(URI::Escape)
Requires:       perl(Class::Accessor::Fast)
Requires:       perl(Class::Data::Inheritable)
Requires:       perl(File::Spec)
Requires:       perl(JSON) >= 2.04
Requires:       perl(Pod::Parser) >= 1.32
Requires:       perl(Pod::ParseUtils)
Requires:       perl(Readonly)
Requires:       perl(Template)
Requires:       perl(URI::Escape)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
AutoReqProv: no

%description
This module allows you to generates CPAN like pod pages from your modules
for your projects. It also creates an optional index page.

%prep
%setup -q -n Pod-ProjectDocs-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes.md cpanfile dist.ini LICENSE Readme.md
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*
%{_bindir}/pod2projdocs

%changelog
* Wed Apr 05 2017 Tom Schoonjans 0.45-1
- Specfile autogenerated by cpanspec 1.78.
