Name:           perl-Wx
Version:        0.9928
Release:        1%{?dist}
Summary:        Interface to the wxWidgets cross-platform GUI toolkit
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Wx/
Source0:        http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-%{version}.tar.gz
Source1:	perl-Wx-provides
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(Alien::wxWidgets) >= 0.25
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(ExtUtils::ParseXS) >= 3.15
BuildRequires:  perl(ExtUtils::XSpp)
BuildRequires:  perl(File::Spec::Functions) >= 0.82
BuildRequires:  perl(Test::Harness) >= 2.26
BuildRequires:  perl(Test::More) >= 0.45
Requires:       perl(Alien::wxWidgets) >= 0.25
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
%(cat %{SOURCE1})

%description
The Wx module is a wrapper for the wxWidgets (formerly known as wxWindows)
GUI toolkit.

%prep
%setup -q -n Wx-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
#make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README.txt typemap.tmpl typemap.xsp wxpl.ico wxpl.xpm Wx.rc
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Wx*
%{_mandir}/man3/*
%{_mandir}/man1/*
%{_bindir}/wxperl_overload

%changelog
* Thu Apr 06 2017 Tom Schoonjans 0.9928-1
- Specfile autogenerated by cpanspec 1.78.
