Name:           perl-Encoding-FixLatin-XS
Version:        1.01
Release:        1%{?dist}
Summary:        XS implementation layer for Encoding::FixLatin
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Encoding-FixLatin-XS/
Source0:        http://www.cpan.org/authors/id/G/GR/GRANTM/Encoding-FixLatin-XS-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 0:5.014
BuildRequires:  perl(Encoding::FixLatin) >= 1.03
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.90
Requires:       perl(Encoding::FixLatin) >= 1.03
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides a C implementation of the 'fix_latin' algorithm. It is
not meant to be called directly. Instead, simply install this module and
use Encoding::FixLatin as normal. Encoding::FixLatin will use this module
if it's found and will fall back to the pure-Perl implementation otherwise.

%prep
%setup -q -n Encoding-FixLatin-XS-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README README.md xt
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Encoding*
%{_mandir}/man3/*

%changelog
* Thu Apr 06 2017 Tom Schoonjans 1.01-1
- Specfile autogenerated by cpanspec 1.78.
